name: Web Build
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run appflow:build
      - run: git config user.email "action@github.com"
      - run: git config user.name "GitHub Action"
      - run: git add -f android/app/src/main/assets/public
      - run: git diff --staged --quiet || git commit -m "chore: web build assets"
      - run: git push
